version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - REGION=us-east-1
      - ACCOUNT_ID=390403865161
      - REPOSITORY_NAME=new-web-app-repo
      - ECR_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
      - REPOSITORY_URI=$ECR_URI/$REPOSITORY_NAME
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_URI
      - IMAGE_TAG=latest

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Build completed successfully.

artifacts:
  files:
    - appspec.yml
    - scripts/*
    - Dockerfile



