version: 0.2

env:
  variables:
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - echo Region: $AWS_DEFAULT_REGION
      - echo Account: $AWS_ACCOUNT_ID
      - echo Repo URL: $ECR_REPOSITORY_URL

      # login
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $ECR_REPOSITORY_URL:$IMAGE_TAG .
      - docker images

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $ECR_REPOSITORY_URL:$IMAGE_TAG
      - echo Build completed successfully.

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - index1.html


